name: Florian Uhlemann
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52784
title: Florian Uhlemann
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171717'
    - '#dda244'
    - '#7a5c2d'
    - '#544123'
    - '#b7863a'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
