layout_spectrum: 0.2098996
typography_spectrum: 0.5170213
color:
  saturation: 0.3638298
  brandStrength: 0.609495
  lightness: 0.7744681
  rhythmicContrast: 1
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: Florian Uhlemann
